/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.40.                      *
*        Compiled Mar 17 2017, 15:33:27                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mute_empty                                            *
* Dimensions:  81 * 62                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



static GUI_CONST_STORAGE unsigned char _acmute_empty[] = {
  /* RLE: 5022 Pixels @ 000,000 */ 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6,
        254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 254, 0xB5, 0xC6, 196, 0xB5, 0xC6,
  0
};  // 40 for 5022 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmute_empty = {
  81, // xSize
  62, // ySize
  162, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acmute_empty,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEM16
};

/*************************** End of file ****************************/
